<!DOCTYPE html>
<html>
    <head>
        <base href="{{site::url}}" />
        <title>{{page::title}}</title>
        <meta name="description" content="{{page::description}}" />
        <meta name="keywords" content="{{page::keywords}}" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="generator" content="Phine CMS; http://www.phine.info" />
    </head>
    <body>
        <div>
            <!-- TODO: Put the areas to the correct position in your layout -->
            _{areas}_
        </div>
    </body>
</html>