<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('Core.ContainerList.Title') ?></h1>
<p>
    <?php TransOut('Core.ContainerList.Description.Amount_{0}', count($this->containers)) ?>
</p>
<?php if ($this->CanCreate()): ?>
<p>
    <a href="<?php HtmlOut($this->FormUrl())?>" class="secondary button fi-plus"> <?php TransOut('Core.ContainerList.New') ?></a>
</p>
<?php endif; ?>
<?php if (count($this->containers) > 0): ?>
<div class="editable-list">
<table>
    <thead>
        <tr>
            <th><?php TransOut('Core.ContainerList.Name') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->containers as $container): ?>
        <tr>
            <td><?php HtmlOut($container->Name); ?></td>
            <td>
                <a class="fa fa-ellipsis-h tiny button" href="<?php HtmlOut($this->ContentTreeUrl($container))?>" title="<?php TransOut('Core.ContainerList.EditContents') ?>"></a>
                <?php if ($this->CanEdit($container)): ?>
                <a class="fa fa-pencil tiny button" href="<?php HtmlOut($this->FormUrl($container)) ?>" title="<?php TransOut('Core.ContainerList.Edit') ?>"></a>
                <?php endif; ?>
                <?php if ($this->CanDelete($container)):?>
                <a href="#" class="delete-link fa fa-remove alert tiny button" data-id="<?php echo $container->GetID(); ?>" data-description="<?php TransOut('Core.ModalDelete.Description.Name_{0}', $container->GetName()) ?>" title="<?php TransOut('Core.ContainerList.Delete') ?>"></a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>
<?php endif; ?>