<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('Core.ContainerContentTree.Title') ?></h1>
<p>
    <?php TransOut('Core.ContainerContentTree.Description') ?>
</p>
<div id="tree" class="editable-tree">
<table>
    <tr class="open" data-tree-id="0">
            <td>
                <a class="tree-toggler"></a>
                <strong><?php HtmlOut($this->container->GetName()); ?>
            </td>
            <td>
                <a class="fa fa-arrow-right tiny secondary button tree-cut-hidden" href="<?php TransOut($this->CreateFormUrl())?>" title="<?php TransOut('Core.ContainerContentTree.CreateStartElement')?>"></a>
                
                <a class="fa fa-arrow-right tree-insert-in tiny button" title="<?php TransOut('Core.ContainerContentTree.InsertIn')?>"></a>
                <a class="fa fa-times tree-clipboard tiny secondary button" title="<?php TransOut('Core.ContainerContentTree.CancelCut')?>"></a>
            </td>
    </tr>
    <?php if ($this->hasContents): ?>
    <?php while ($containerContent = $this->NextContainerContent()):?>
    <?php $branch = new Phine\Bundles\Core\Snippets\TreeBranches\ContainerContentBranch($containerContent); ?>
    <?php echo $branch->Render(); ?>
    <?php endwhile; ?>
    <?php endif; ?>
</table>
</div>