<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back') ?>"></a><?php TransOut('Core.MembergroupForm.Title') ?></h1>
<p>
    <?php TransOut('Core.MembergroupForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('Core.MembergroupForm.Legend') ?></legend>
        <?php echo $this->RenderElement('Name'); ?>
    </fieldset>
    <?php echo $this->RenderSubmit(); ?>
</form>