<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('Core.PageTree.Title') ?></h1>
<p>
    <?php TransOut('Core.PageTree.Description') ?>
</p>
<div id="tree" class="editable-tree">
<table>
    <tr class="open" data-tree-id="0">
             
            <td>
                <a class="tree-toggler"></a>
                <strong><?php HtmlOut($this->site->GetName()) ?></strong>
            </td>
            <td>
                <?php if ($this->CanCreateIn()): ?>
                <a class="fa fa-arrow-right tiny secondary button tree-cut-hidden" href="<?php TransOut($this->CreateFormUrl())?>" title="<?php TransOut('Core.PageTree.CreateStartPage')?>"></a>
                <a class="fa fa-arrow-right tree-insert-in tiny button" title="<?php TransOut('CorePageTree.InsertIn')?>"></a>
                <?php endif; ?>
                <a class="fa fa-times tree-clipboard tiny secondary button" title="<?php TransOut('CorePageTree.CancelCut')?>"></a>
            </td>
    </tr>
    <?php if ($this->hasPages):?>
    <?php while ($page = $this->NextPage()):?>
    <?php $branch = new Phine\Bundles\Core\Snippets\TreeBranches\PageBranch($page); ?>
    <?php echo $branch->Render(); ?>
    <?php endwhile; ?>
    <?php endif; ?>
</table>
</div>