<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back') ?>"></a><?php TransOut('Core.SettingsForm.Title') ?></h1>
<p>
    <?php TransOut('Core.SettingsForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('Core.SettingsForm.Legend') ?></legend>
        <?php echo $this->RenderElement('LogLifetime'); ?>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('MailFromEMail'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('MailFromName'); ?>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend><?php TransOut('Core.SettingsForm.Smtp.Legend')?></legend>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('SmtpHost'); ?>
            </div>
            <div class="medium-3 columns">
                <?php echo $this->RenderElement('SmtpPort'); ?>
            </div>
            <div class="medium-3 columns">
                <?php echo $this->RenderElement('SmtpSecurity'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('SmtpUser'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('SmtpPassword'); ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderSubmit(); ?>
</form>