<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('Core.SiteForm.Title') ?></h1>
<p>
    <?php TransOut('Core.SiteForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('Core.SiteForm.Legend') ?></legend>
        <?php echo $this->RenderElement('Name'); ?>
        <?php echo $this->RenderElement('Url'); ?>
        <?php echo $this->RenderElement('BaseUrl'); ?>
        <?php echo $this->RenderElement('Language'); ?>
    </fieldset>
    <fieldset>
        <legend><?php TransOut('Core.SiteForm.Access.Legend') ?></legend>
        <?php if ($this->CanAssignGroup()): ?>
        <?php echo $this->RenderElement('UserGroup'); ?>
        <div id="group-rights">
            <?php echo $this->siteRights->Render(); ?>
        </div>
        <?php endif; ?>
    </fieldset>
    <fieldset>
        <legend><?php TransOut('Core.SiteForm.Sitemap.Legend') ?></legend>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('SitemapActive'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('SitemapCacheLifetime'); ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderSubmit(); ?>
</form>