<div class="row">
    <div class ="medium-3 columns">
        <?php echo $this->RenderCheckbox('Move'); ?>
    </div>
    <div class ="medium-3 columns">
        <?php echo $this->RenderCheckbox('Edit'); ?>
    </div>
    <div class ="medium-3 columns">
        <?php echo $this->RenderCheckbox('Remove'); ?>
    </div>
    <div class ="medium-3 columns">
        <?php echo $this->RenderCheckbox('CreateIn'); ?>
    </div>
</div>
<?php echo $this->contentRights->Render(); ?>