<script>
    $(function(){
        var button = $('#<?php HtmlOut($this->prefix)?>OpenModal');
        $(button).click(function(e){
            e.preventDefault();
            var data = new Object();
            data['prefix'] = '<?php HtmlOut($this->prefix) ?>';
            data['page'] = $('#<?php HtmlOut($this->prefix . 'Page') ?>').val();
            data['params'] = $('#<?php HtmlOut($this->prefix) ?>Params').val();
            data['fragment'] = $('#<?php HtmlOut($this->prefix) ?>Fragment').val();
            $('#ajax-modal').foundation('reveal', 'open', 
                '<?php echo($this->OpenUrl()); ?>&' + $.param(data));
        });
    });
</script>