<?php $field = $this->field; ?>
<?php $name = $field->GetName() ?>
<input <?php foreach($this->attribs as $attrName=>$attrValue): ?> <?php echo $attrName ?>="<?php HtmlOut($attrValue)?>"<?php endforeach; ?> type="<?php echo HtmlOut($field->GetType()) ?>" name="<?php echo $name ?>"<?php if ($field->CheckFailed()): ?> class="error"<?php endif; ?> id="<?php echo $name?>" value="<?php HtmlOut($field->GetValue())?>" />
<?php if ($field->CheckFailed()): ?>
<small class="error">
    <?php foreach ($field->GetValidators() as $validator): ?>
    <?php $error = $validator->GetError() ?>
    <?php if ($error): ?>
    <span>
        <?php HtmlOut($validator->GetError()); ?>
    </span>
    <?php endif; ?>
    <?php endforeach ?>
</small>
<?php endif; ?>