<?php
    $field = $this->field;
    $name = $field->GetName();
?>
<fieldset<?php foreach($this->attribs as $attrName=>$attrValue): ?> <?php echo $attrName ?>="<?php echo HtmlOut($attrValue)?>"<?php endforeach; ?>>
    <legend><?php HtmlOut($field->GetLabel()) ?></legend>
    <?php $idx = 1; ?>
    <?php foreach ($field->GetOptions() as $value=>$text): ?>
        <?php $labelAttribs = $field->GetLabelAttributes($value);?>
        <label for="<?php HtmlOut($name) ?>-<?php HtmlOut($idx) ?>"<?php foreach($labelAttribs as $attrName=>$attrValue): ?> <?php echo $attrName ?>="<?php echo HtmlOut($attrValue)?>"<?php endforeach; ?>>
            <?php $fieldAttribs = $field->GetButtonAttributes($value); ?>
            <input name="<?php HtmlOut($name) ?>" id="<?php HtmlOut($name) ?>-<?php HtmlOut($idx) ?>" type="radio" value="<?php HtmlOut($value) ?>"<?php if ($field->IsSelected($value)): ?> checked="checked"<?php endif; ?><?php foreach($fieldAttribs as $attrName=>$attrValue): ?> <?php echo $attrName ?>="<?php echo HtmlOut($attrValue)?>"<?php endforeach; ?> />
            <?php HtmlOut($text) ?>
        </label>
    <?php ++$idx; endforeach; ?>
    <?php if ($field->CheckFailed()): ?>
    <small class="error">
        <?php foreach ($field->GetValidators() as $validator): ?>
        <?php $error = $validator->GetError() ?>
        <?php if ($error): ?>
        <span>
            <?php HtmlOut($validator->GetError()); ?>
        </span>
        <?php endif; ?>
        <?php endforeach ?>
    </small>
    <?php endif; ?>
</fieldset>