<?php $field = $this->field; ?>
<?php $name = $field->GetName() ?>
<?php if ($this->field->GetLabel()): ?>
<label for ="<?php echo $name?>"<?php if($field->CheckFailed()): ?> class="error"<?php endif; ?>><?php HtmlOut($field->GetLabel()) ?></label>
<?php endif; ?>
<input <?php foreach($this->attribs as $attrName=>$attrValue): ?> <?php echo $attrName ?>="<?php HtmlOut($attrValue)?>"<?php endforeach; ?> type="<?php HtmlOut($field->GetType()) ?>" name="<?php echo $name?>"<?php if($field->CheckFailed()): ?> class="error"<?php endif; ?> id="<?php echo $name?>" value="<?php HtmlOut($field->GetValue())?>" />
<?php if ($field->CheckFailed()): ?>
<small class="error">
    <?php foreach ($field->GetValidators() as $validator): ?>
    <?php $error = $validator->GetError() ?>
    <?php if ($error): ?>
    <span>
        <?php HtmlOut($error); ?>
    </span>
    <?php endif; ?>
    <?php endforeach ?>
</small>
<?php endif; ?>